const FETCH_PRIVILEGES_REQUESTED = 'FETCH_PRIVILEGES_REQUESTED'
const FETCH_PRIVILEGES_FAILED = 'FETCH_PRIVILEGES_FAILED'
const FETCH_PRIVILEGES_SUCCEEDED = 'FETCH_PRIVILEGES_SUCCEEDED'

export {
  FETCH_PRIVILEGES_REQUESTED,
  FETCH_PRIVILEGES_FAILED,
  FETCH_PRIVILEGES_SUCCEEDED,
}
