const FETCH_ACCOUNTS_REQUESTED = 'FETCH_ACCOUNTS_REQUESTED'
const FETCH_ACCOUNTS_FAILED = 'FETCH_ACCOUNTS_FAILED'
const FETCH_ACCOUNTS_SUCCEEDED = 'FETCH_ACCOUNTS_SUCCEEDED'

export {
  FETCH_ACCOUNTS_REQUESTED,
  FETCH_ACCOUNTS_FAILED,
  FETCH_ACCOUNTS_SUCCEEDED,
}
